name: 'Falco Action'
description: 'Run Falco in a GitHub action'
author: 'darryk10'
inputs:
  config_file:
    description: 'start action config file'
    required: false
    default: '${{github.action_path}}/.sysdig/ignore.config'
runs:
  using: 'composite'
  steps:
  - name: Sysdig
    if: ${{inputs.start == 'true' }}
    shell: bash
    run: |
      echo "Running Sysdig"

      echo "${{inputs.config_file}}"
      #IGNORE_FILTER_FOLDER=${{github.action_path}}/.sysdig
      #IGNORE_FILTER_FOLDER="$GITHUB_WORKSPACE/.sysdig"
      #CONFIG_FILE="$IGNORE_FILTER_FOLDER/ignore.config"

      if [ ! -e "${{inputs.config_file}}" ]; then
        echo "Config File does not exist."
        exit 1
      fi

      ##create filters
      IGNORE_IPS_FILTER="and not fd.sip in ( $(jq -r -f $IGNORE_FILTER_FOLDER/ignore_ips.jq $CONFIG_FILE) ) "
      echo $IGNORE_IPS_FILTER
      IGNORE_FOLDERS_FILTER="and not fd.directory in ( $(jq -r -f $IGNORE_FILTER_FOLDER/ignore_folders.jq $CONFIG_FILE) ) "
      echo $IGNORE_FOLDERS_FILTER
      IGNORE_FILES_FILTER="and not fd.name in ( $(jq -r -f $IGNORE_FILTER_FOLDER/ignore_files.jq $CONFIG_FILE) ) "
      echo $IGNORE_FILES_FILTER
      IGNORE_SYSCALLS_FILTER="and not evt.type in ( $(jq -r -f $IGNORE_FILTER_FOLDER/ignore_syscalls.jq $CONFIG_FILE) ) "
      echo $IGNORE_SYSCALLS_FILTER
      IGNORE_PROCESSES_FILTER="and not proc.name in ( $(jq -r  -f $IGNORE_FILTER_FOLDER/ignore_processes.jq $CONFIG_FILE) ) "
      echo $IGNORE_PROCESSES_FILTER

      docker run --rm -d --name sysdig --privileged \
      -v /var/run/docker.sock:/host/var/run/docker.sock \
      -v /dev:/host/dev -v /proc:/host/proc:ro \
      -v /boot:/host/boot:ro \
      -v /lib/modules:/host/lib/modules:ro \
      -v /usr:/host/usr:ro \
      -v ${{inputs.mount_dir}}:${{inputs.mount_dir}} \
      --net=host sysdig/sysdig:latest sysdig --modern-bpf -w /tmp/falco_events.json "not evt.type in (switch) $IGNORE_SYSCALLS_FILTER $IGNORE_PROCESSES_FILTER $IGNORE_FOLDERS_FILTER $IGNORE_FILES_FILTER"
      echo "Sysdig started"

      # Ensure Falco is running
      sleep 10
      docker ps -a 
      docker logs sysdig