on:
  workflow_dispatch:

jobs:
  test-falco:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Falco
      uses: darryk10/falco-action/falco@test-falco-simple-mode
      with:
        custom-rule-file: ${{ github.workspace }}/rules/falco_cicd_rules.yaml

    - name: Overwrite Source Code
      shell: bash
      run: |
        echo "pwned" > ${{ github.workspace }}/pwn.txt
